### PR TITLE
Added test for social media links

### PR DESCRIPTION
**Pull request by DevOps-Team5-2022**
Created pull request for Samuel

### CODE REVIEW

**Review by elginloh — APPROVED** [review]
Create pull request for Samuel Test Case

**Review by elginloh — CHANGES_REQUESTED** [review]
Please include your code in the FeedbackTest.py file using a function and commit and push your changes again

**Review by Kevin-Khew — APPROVED** [review]
Removed extra "SocialMediaTest.py" file. Renamed Samuel's test case function

**Review by elginloh — APPROVED** [review]
ready to be merged to main branch

**Pull request merged**
